### ISSUE TITLE
Compatibility with Elan Precision Devices

### ISSUE THREAD

**Issue by williambj1** [gokula/ELANSMBus#1]
Hello, gokula!

I have a `ELAN1404` trackpad which is an **Elan Precision Trackpad (PTP)**.
In Linux, my trackpad works quite well with all the fingers and gestures. 
Before using this kext, I want to know whether **Elan Precision Trackpads** are supported (Because they are not supported on [VoodooI2CELAN](https://github.com/kprinssu/VoodooI2CELAN)).
I'm using a laptop which has a CFL processor, and ConnonLake GPIO Interrupt is not supported yet on [VoodooGPIO](https://github.com/coolstar/VoodooGPIO).

By the way, is this a satellite of VoodooI2C or it's a **separate** kext? 

Will this kext help me?

Thank you very much!

**Comment by gokula** [comment]
Hello, this is a separate kext. It uses the same protocol as VoodooI2CElan, so unfortunately your trackpad will probably not work.
