### ISSUE TITLE
AppleLpssiI2C.kext

### ISSUE THREAD

**Issue by vistree** [gokula/ELANSMBus#2]
Hi @gokula ,
great to see this project. I'm also using the t480s and I'm not really happy about the existing touchpad solutions. Rehabmans voodooPS2 is great for keyboard and Trackpoint - but there is no scrolling available for the touchpad.
There is an alternative ApplePS2SmartTouchPad.kext available here on github - but I have lots of trouble with that kext, as the touchpad seems to sensitive (cursor jumps if you type), keyboard layout is not fully working (voodooPS2 is better here) and trackpoint will never work. 
So I'm looking forward to test your new kext. I had a look at your install instructions and where wondering about the removal of AppleLpssiI2C.kext . Is that the correct name? Because I can't find it on my machine.

**Comment by vistree** [comment]
sudo kextcache -i /
AppleIntelLpssI2CController.kext - dependency 'com.apple.driver.AppleIntelLpssI2C' not found.
AppleIntelLpssI2CController.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
AppleIntelLpssI2CController.kext - dependency 'com.apple.driver.AppleIntelLpssI2C' not found.
AppleHPM.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
KernelCache ID: E076B25046348294EC1D923FC03F5695
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fd0b8295690 [0x7fff87ea78f0]> { URL = "ELANSMBus.kext/ -- file:///Library/Extensions/", ID = "com.gokula.ELANSMbus" }

**Comment by gokula** [comment]
Hi, there was a typo in the kext name, the right one is included now. (AppleIntelLpssiI2C.kext)
Don't forget to fix the permissions of the ELANSMBus.kext before updating the kextcache

**Comment by vistree** [comment]
Now you added 2 times the same kext name ...

**Comment by vistree** [comment]
Do we maybe need to remove AppleIntelLpssI2CController.kext?

**Comment by gokula** [comment]
👍

**Comment by vistree** [comment]
So, I prepared everything regarding your instructions - but touchpad does not work. I copied the ELANSMBus.kext to /L/E and user "Kext Utility" to check and correct permissions. Afterward I did
sudo kextcache -i /
OUTPUT:
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fde126df100 [0x7fff8bcfd8f0]> { URL = "ELANSMBus.kext/ -- file:///Library/Extensions/", ID = "com.gokula.ELANSMbus" }
AppleHPM.kext - dependency 'com.apple.driver.AppleIntelLpssI2CController' not found.
AppleHPM.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
KernelCache ID: 93E1AC26FBF45F5E3D09D0DAEF028ED3
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fe5b7868900 [0x7fff8bcfd8f0]> { URL = "ELANSMBus.kext/ -- file:///Library/Extensions/", ID = "com.gokula.ELANSMbus" }
How can I debug now to find the problem?

**Comment by gokula** [comment]
Did you also included the hotpatch? What’s attached to the SBUS device in IOreg?

**Comment by vistree** [comment]
I added the info from patchtes file to 
<key>KextsToPatch</key>
		<array>
of my config.plist. Is this right? Tried also to put it to the 
<key>Patches</key>
			<array>
which makes no difference.

SSDT-SMBUS.dsl and SSDT-SMBUS.aml are in place

Searching for smb in IORegistryExplorer I get the following information:
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SBUS@1F,4/AppleSMBusPCI/BUS0@0/AppleSMBusControllerICH/DVL0

with: 
_ADR             Number       0x15
_STA              Number       0xffffffff
compatible    Data            <"diagsvault">
device-properties
                       acpi-device        string       IOACPIPlatformDevice is not serializable
                       acpi-path            string       IOACPIPlane:/_SB/PCI0@0/SBUS@1f0004/BUS0@0/DVL0@15
                       address              number     0x15

Hope, this is the correct information you are requesting?!

**Comment by gokula** [comment]
Hello, it seems the ELANSMBus is not loaded, can you try again with the latest release? (1.1)

**Comment by vistree** [comment]
Version 1.1 works ;-) Thank you!!!
I will close this issue and will come back with some feedback in a new issue.
