### ISSUE TITLE
Error in To Do

### ISSUE THREAD

**Issue by vistree** [gokula/ELANSMBus#3]
It seems, that there is an error in the To Do area:
"Find how to avoid the deletion of AppleSMBusPCI and AppleSMBusControllerkexts (more elegant)." must be changed into:
"Find how to avoid the deletion of AppleIntelLpssiI2C.kextand and AppleIntelLpssiI2CController.kext (more elegant)."
as you already provide a patch for AppleSMBusPCI and AppleSMBusControllerkexts through config.plist settings.

**Comment by gokula** [comment]
I will fix it. Thanks!
