### ISSUE TITLE
Touchpad not working after suspend

### ISSUE THREAD

**Issue by vistree** [gokula/ELANSMBus#6]
If I set my laptop to suspend the touchpad does not work any more after waking the laptop up. Maybe this is related to the power management you mentioned in your To Do?

**Comment by gokula** [comment]
Yes, it's not implemented yet.

**Comment by vistree** [comment]
I think this is the most important thing to look after, because if you use a laptop you normally want to suspend (e.g. by closing the lid).

**Comment by vistree** [comment]
Any progress? Any way I can help?

**Comment by leo-labs** [comment]
I worked on a rewrite the last days and now there is a new driver at https://github.com/leo-labs/VoodooSMBus/ that should be able to work after suspend

**Comment by vistree** [comment]
I moved to the project of leo-labs https://github.com/leo-labs/VoodooSMBus/ which solves this problem ;-)
